apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-frontend
  namespace: todo

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: todo-frontend

  template:
    metadata:
      labels:
        app: todo-frontend

    spec:
      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          ports:
            - containerPort: 80