apiVersion: v1
kind: Secret

# metadata:
#   name: postgres-secret
#   namespace: todo

metadata:
  name: postgres-secret
  namespace: todo
  annotations:
    argocd.argoproj.io/sync-options: Prune=false

type: Opaque

stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}